name: CI

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'pnpm'
    - run: pnpm add -g pnpm
    - run: pnpm install
    - run: pnpm build
    - name: pnpm build
      run: pnpm build
    - name: pnpm test
      run: pnpm test
    - name: codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        name: codecove # optional
        flags: unittest
        fail_ci_if_error: false # optional (default = false)
        #directory: ./coverage/reports/
        #files: ./coverage1.xml,./coverage2.xml
        verbose: true # optional (default = false)
